/**
 * Expo config plugin: Google Play upload-key signing for release builds (ADR-054).
 *
 * `android/` is generated by `expo prebuild`, so the signing config is injected here rather than edited by hand.
 * Credentials are read at build time from a properties file outside the repository:
 *   $CLINNOTE_SIGNING_PROPERTIES, or Gradle property `clinnote.signingProperties`,
 *   or ~/.clinnote-signing/signing.properties (created by scripts/create-upload-key.sh).
 * Nothing secret is written into the generated project. If the file is missing or incomplete, every release
 * assemble/bundle/package task fails: there is no fallback to the debug key.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @clinnote release-signing';

const HELPER = `${MARKER}
def clinnoteSigningFile = file(System.getenv('CLINNOTE_SIGNING_PROPERTIES') ?: findProperty('clinnote.signingProperties') ?: "\${System.getProperty('user.home')}/.clinnote-signing/signing.properties")
def clinnoteSigning = new Properties()
if (clinnoteSigningFile.exists()) { clinnoteSigningFile.withInputStream { clinnoteSigning.load(it) } }
def clinnoteHasReleaseSigning = ['storeFile', 'storePassword', 'keyAlias', 'keyPassword'].every { clinnoteSigning.getProperty(it) } && file(clinnoteSigning.getProperty('storeFile')).exists()

gradle.taskGraph.whenReady { graph ->
    def releaseTasks = graph.allTasks.findAll { it.project == project && it.name ==~ /(assemble|bundle|package|sign).*Release.*/ }
    if (!clinnoteHasReleaseSigning && !releaseTasks.isEmpty()) {
        throw new GradleException("ClinNote release signing is not configured: \${clinnoteSigningFile} is missing or incomplete. Refusing to sign a release with the debug key. See docs/GOOGLE-PLAY.md §11.")
    }
}

android {`;

const DEBUG_SIGNING = `            keyPassword 'android'
        }
    }`;

const RELEASE_SIGNING = `            keyPassword 'android'
        }
        if (clinnoteHasReleaseSigning) {
            release {
                storeFile file(clinnoteSigning.getProperty('storeFile'))
                storePassword clinnoteSigning.getProperty('storePassword')
                keyAlias clinnoteSigning.getProperty('keyAlias')
                keyPassword clinnoteSigning.getProperty('keyPassword')
            }
        }
    }`;

const RELEASE_BUILDTYPE = /(release \{\n(?:\s*\/\/[^\n]*\n)*\s*)signingConfig signingConfigs\.debug/;

function applyReleaseSigning(gradle) {
  if (gradle.includes(MARKER)) return gradle;
  const steps = [
    ['android block', (g) => g.replace(/^android \{/m, HELPER)],
    ['signingConfigs', (g) => g.replace(DEBUG_SIGNING, RELEASE_SIGNING)],
    ['release buildType', (g) => g.replace(RELEASE_BUILDTYPE, '$1signingConfig clinnoteHasReleaseSigning ? signingConfigs.release : null')],
  ];
  return steps.reduce((g, [name, step]) => {
    const next = step(g);
    if (next === g) throw new Error(`withReleaseSigning: could not find the ${name} in android/app/build.gradle; the Expo template changed. Update the plugin.`);
    return next;
  }, gradle);
}

module.exports = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') throw new Error('withReleaseSigning: expected a Groovy build.gradle');
    cfg.modResults.contents = applyReleaseSigning(cfg.modResults.contents);
    return cfg;
  });

module.exports.applyReleaseSigning = applyReleaseSigning;
