/**
 * Code-owned lexicons and cue lists (AI.md §5.1 rules 9, 16, 17, 19; ADR-044). Extending a list is a tested code
 * change; the rules themselves are never relaxed. Terms are lower case and matched on word boundaries.
 */

export const NEGATION_CUES = [
  'no',
  'not',
  'denies',
  'denied',
  'deny',
  'without',
  'never',
  'negative for',
  'absent',
  'free of',
  "don't",
  'dont',
  "doesn't",
  'doesnt',
  "didn't",
  'didnt',
  "haven't",
  'havent',
  "hasn't",
  'hasnt',
  "isn't",
  "wasn't",
  "aren't",
  'none',
  'nil',
];

export const HEDGE_CUES = [
  'maybe',
  'i think',
  'not sure',
  'possibly',
  'possible',
  'might',
  'may',
  'perhaps',
  'probably',
  'unlikely',
  'doubt',
  'could be',
  'kind of',
  'sort of',
  'i guess',
  'suspect',
];

export const HYPOTHETICAL_CUES = ['if', 'in case', 'should you', 'return if', 'come back if', 'watch for', 'unless', 'whenever'];

export const FAMILY_MEMBERS = [
  'mother',
  'mom',
  'mum',
  'father',
  'dad',
  'brother',
  'sister',
  'son',
  'daughter',
  'wife',
  'husband',
  'aunt',
  'uncle',
  'grandmother',
  'grandfather',
  'grandma',
  'grandpa',
  'cousin',
  'parents',
  'friend',
  'partner',
  'family',
];

export const QUESTION_OPENERS = [
  'have you',
  'do you',
  'did you',
  'are you',
  'were you',
  'any',
  'is there',
  'is it',
  'does it',
  'does this',
  'how long',
  'how often',
  'how much',
  'how many',
  'when did',
  'when was',
  'what',
  'where',
  'which',
  'can you',
  'could you',
  'would you',
  'any history',
];

/** Inferential, diagnostic or treatment wording (rule 17c): allowed only verbatim from the cited source. */
export const INFERENTIAL_WORDING = [
  'likely',
  'probable',
  'probably',
  'possible',
  'consistent with',
  'suggestive of',
  'suggests',
  'rule out',
  'ruled out',
  'diagnosis of',
  'diagnosed',
  'start',
  'started',
  'stop',
  'increase',
  'decrease',
  'prescribe',
  'prescribed',
  'recommend',
  'should take',
];

export const STOPWORDS = new Set(
  'a an the and or of for to in on at by with from my your his her their our its is are was were be been being have has had i you he she we they it this that these those about approximately around some any very really just also then so as do does did am up over under into per since ago'.split(
    ' ',
  ),
);

/** Synonym → canonical concept key. Canonical keys map to themselves implicitly. */
export const SYNONYMS: Record<string, string> = {
  coughing: 'cough',
  'dry cough': 'cough',
  'productive cough': 'cough',
  'night cough': 'cough',
  'shortness of breath': 'shortness of breath',
  breathless: 'shortness of breath',
  breathlessness: 'shortness of breath',
  sob: 'shortness of breath',
  dyspnea: 'shortness of breath',
  dyspnoea: 'shortness of breath',
  temperature: 'fever',
  fevers: 'fever',
  feverish: 'fever',
  pyrexia: 'fever',
  'night sweats': 'night sweats',
  sweating: 'sweating',
  'losing weight': 'weight loss',
  'lost weight': 'weight loss',
  'weight loss': 'weight loss',
  'chest pains': 'chest pain',
  headaches: 'headache',
  'stomach ache': 'abdominal pain',
  'stomach pain': 'abdominal pain',
  'tummy pain': 'abdominal pain',
  'belly pain': 'abdominal pain',
  'throwing up': 'vomiting',
  vomit: 'vomiting',
  'feeling sick': 'nausea',
  tired: 'fatigue',
  tiredness: 'fatigue',
  exhausted: 'fatigue',
  dizzy: 'dizziness',
  'blood in sputum': 'haemoptysis',
  'coughing up blood': 'haemoptysis',
  hemoptysis: 'haemoptysis',
  'high blood pressure': 'hypertension',
  'blood pressure problem': 'hypertension',
  'high bp': 'hypertension',
  sugar: 'diabetes',
  diabetic: 'diabetes',
  'diabetes mellitus': 'diabetes',
  'type 2 diabetes': 'diabetes',
  'type 1 diabetes': 'diabetes',
  'heart attack': 'myocardial infarction',
  tb: 'tuberculosis',
  'kidney disease': 'chronic kidney disease',
  'acid reflux': 'gastro-oesophageal reflux',
  reflux: 'gastro-oesophageal reflux',
  gerd: 'gastro-oesophageal reflux',
  'high cholesterol': 'hyperlipidaemia',
  cholesterol: 'hyperlipidaemia',
  'x-ray': 'chest x-ray',
  'chest xray': 'chest x-ray',
  'blood count': 'full blood count',
  cbc: 'full blood count',
  fbc: 'full blood count',
  a1c: 'hba1c',
  'hemoglobin a1c': 'hba1c',
  'sugar test': 'hba1c',
};

export const SYMPTOMS = [
  'cough',
  'fever',
  'chills',
  'night sweats',
  'sweating',
  'weight loss',
  'weight gain',
  'fatigue',
  'shortness of breath',
  'wheeze',
  'wheezing',
  'chest pain',
  'chest tightness',
  'palpitations',
  'haemoptysis',
  'sputum',
  'phlegm',
  'sore throat',
  'runny nose',
  'headache',
  'dizziness',
  'fainting',
  'nausea',
  'vomiting',
  'diarrhoea',
  'diarrhea',
  'constipation',
  'abdominal pain',
  'heartburn',
  'back pain',
  'joint pain',
  'muscle pain',
  'rash',
  'itching',
  'swelling',
  'numbness',
  'tingling',
  'weakness',
  'blurred vision',
  'loss of appetite',
  'difficulty swallowing',
  'frequent urination',
  'painful urination',
  'thirst',
  'insomnia',
  'anxiety',
  'low mood',
  'ear pain',
  'leg swelling',
  'bleeding',
  'bruising',
  'confusion',
];

export const CONDITIONS = [
  'diabetes',
  'hypertension',
  'asthma',
  'copd',
  'tuberculosis',
  'pneumonia',
  'bronchitis',
  'heart failure',
  'atrial fibrillation',
  'myocardial infarction',
  'angina',
  'stroke',
  'epilepsy',
  'migraine',
  'depression',
  'anxiety disorder',
  'hypothyroidism',
  'hyperthyroidism',
  'chronic kidney disease',
  'gastro-oesophageal reflux',
  'hyperlipidaemia',
  'obesity',
  'osteoarthritis',
  'rheumatoid arthritis',
  'gout',
  'anaemia',
  'anemia',
  'hiv',
  'hepatitis',
  'cancer',
  'lung cancer',
  'breast cancer',
  'colon cancer',
  'prostate cancer',
  'lymphoma',
  'leukaemia',
  'sleep apnoea',
  'covid-19',
  'influenza',
  'allergic rhinitis',
  'eczema',
  'psoriasis',
];

/** Cancer concept list for the CANCER_INFO route (EVIDENCE-SOURCES §17; only HISTORY_MEDICAL / ASSESSMENT). */
export const CANCER_CONCEPTS = new Set([
  'cancer',
  'lung cancer',
  'breast cancer',
  'colon cancer',
  'prostate cancer',
  'lymphoma',
  'leukaemia',
]);

/** Common generic medication names (synthetic-data friendly). Unknown names fall back to dose patterns. */
export const MEDICATIONS = [
  'metformin',
  'gliclazide',
  'insulin',
  'sitagliptin',
  'empagliflozin',
  'amlodipine',
  'lisinopril',
  'ramipril',
  'losartan',
  'enalapril',
  'bisoprolol',
  'atenolol',
  'metoprolol',
  'hydrochlorothiazide',
  'furosemide',
  'atorvastatin',
  'simvastatin',
  'rosuvastatin',
  'aspirin',
  'clopidogrel',
  'warfarin',
  'apixaban',
  'rivaroxaban',
  'paracetamol',
  'acetaminophen',
  'ibuprofen',
  'naproxen',
  'codeine',
  'tramadol',
  'morphine',
  'amoxicillin',
  'co-amoxiclav',
  'azithromycin',
  'clarithromycin',
  'doxycycline',
  'ciprofloxacin',
  'cefalexin',
  'nitrofurantoin',
  'salbutamol',
  'albuterol',
  'budesonide',
  'fluticasone',
  'montelukast',
  'tiotropium',
  'prednisolone',
  'prednisone',
  'omeprazole',
  'pantoprazole',
  'lansoprazole',
  'ranitidine',
  'levothyroxine',
  'sertraline',
  'fluoxetine',
  'citalopram',
  'amitriptyline',
  'gabapentin',
  'pregabalin',
  'cetirizine',
  'loratadine',
  'allopurinol',
  'folic acid',
  'vitamin d',
  'iron',
];

export const ALLERGENS = [
  'penicillin',
  'amoxicillin',
  'sulfa',
  'sulphonamides',
  'aspirin',
  'ibuprofen',
  'nsaids',
  'codeine',
  'latex',
  'peanuts',
  'nuts',
  'shellfish',
  'eggs',
  'iodine',
  'contrast',
];

export const INVESTIGATIONS = [
  'chest x-ray',
  'x-ray',
  'ct scan',
  'mri',
  'ultrasound',
  'ecg',
  'echocardiogram',
  'blood test',
  'blood tests',
  'full blood count',
  'hba1c',
  'kidney function',
  'liver function',
  'thyroid function',
  'cholesterol test',
  'lipid profile',
  'urine test',
  'sputum test',
  'sputum culture',
  'spirometry',
  'covid test',
  'blood sugar',
  'crp',
  'esr',
];

export const EXAM_TERMS = [
  'chest is clear',
  'chest clear',
  'crackles',
  'crepitations',
  'wheeze on auscultation',
  'tender',
  'tenderness',
  'murmur',
  'oedema',
  'edema',
  'lymph nodes',
  'on examination',
  'clubbing',
  'reduced air entry',
  'breath sounds',
];

/** Code-owned pattern entries of the normalization table (rule 16): applied to the fact's own value only. */
export const PATTERN_CONCEPTS: [RegExp, string][] = [
  [/^(?:i'?ve |i have |have )?(?:lost|losing|lose)\s+(?:about |around |approximately |nearly )?\d+(?:\.\d+)?\s*(?:kg|kilos?|kilograms?|pounds|lbs)$/i, 'weight loss'],
];

/** Canonical form for a phrase (rule 16): lower case, synonyms mapped. Returns null when not in any table. */
export function canonicalConcept(phrase: string): string | null {
  const p = phrase.toLowerCase().trim();
  for (const [re, concept] of PATTERN_CONCEPTS) if (re.test(p)) return concept;
  if (SYNONYMS[p]) return SYNONYMS[p];
  if (SYMPTOMS.includes(p) || CONDITIONS.includes(p) || MEDICATIONS.includes(p) || ALLERGENS.includes(p) || INVESTIGATIONS.includes(p))
    return p;
  return null;
}

export const NUMBER_WORDS: Record<string, number> = {
  zero: 0,
  one: 1,
  a: 1,
  an: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  eleven: 11,
  twelve: 12,
  thirteen: 13,
  fourteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  nineteen: 19,
  twenty: 20,
  thirty: 30,
  forty: 40,
  fifty: 50,
  sixty: 60,
  seventy: 70,
  eighty: 80,
  ninety: 90,
  hundred: 100,
  thousand: 1000,
};
